### ISSUE TITLE
Improve client library test performance

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#764] opened 2017-04-26 17:34 UTC
Per discussion with @SahilTikale @naved001 @kylehogan , we'd like to refactor tests to be able to operate in parallel.

Right now this includes:
- [ ] [Client library tests](https://github.com/CCI-MOC/hil/blob/master/tests/unit/client.py) can spawn a different web server for each test, each on its own port. Picking a port could be done either sequentially or randomly, first checking to see if the port is already bound to.
- [ ] Maybe keystone (I've heard @zenhack has ideas on this)

**Comment by zenhack** [comment] 2017-04-26 19:20
I started some work on this on a branch, but it's blocked by the outright failures we're having. The basic notion I had was to split up our tests into a larger matrix, so e.g. the keystone and apache tests run separately from tests/unit, and thus all of that installation doesn't need to happen in unit, and fewer tests need to be run in those cases.

**Comment by henn** [comment] 2017-05-10 18:13
Tests running with postgres are currently unable to run in parallel due to sharing a single DB.

To overcome this (allowing us to run unit tests in parallel with `py.test -n auto --boxed`), each worker process could have its own DB named after its worker name. [Pytest-xdist's docs](https://github.com/pytest-dev/pytest-xdist#identifying-the-worker-process-during-a-test) describe how to do this.

**Comment by zenhack** [comment] 2017-05-10 18:46
I'm going to submit a PR doing the keystone stuff (and some other componentization); I started working on it while we were fussing with the transient failures, but was blocked on the fix.

**Comment by zenhack** [comment] 2017-05-10 19:10
So, at this point tests/unit/client.py even on sqlite3 is taking longer than the rest of the tests put together -- including the keystone test and apache, and their setup steps. I'm going to do the keystone breakout anyway, since I think it will pay off once we fix that, but this is just dumb -- there's something deeper going on than "we should start parallelizing," those tests should *not* be that slow.

**Comment by zenhack** [comment] 2017-05-10 20:07
The time is being eaten up by populate_server() -- it takes about 40 seconds to run on my laptop.

**Comment by zenhack** [comment] 2017-05-10 20:48
...which amounts to about  0.67 requests per second. I'm also getting a whole bunch of this:

```
connectionpool.py          395 DEBUG    "PUT /switch/mock-01/port/gi1/0/3 HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /switch/mock-01/port/gi1/0/3/connect_nic HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /switch/mock-01/port/gi1/0/4 HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /switch/mock-01/port/gi1/0/4/connect_nic HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /switch/mock-01/port/gi1/0/5 HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /switch/mock-01/port/gi1/0/5/connect_nic HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /switch/mock-01/port/gi1/0/6 HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /switch/mock-01/port/gi1/0/6/connect_nic HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /switch/mock-01/port/gi1/0/7 HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /switch/mock-01/port/gi1/0/7/connect_nic HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /switch/mock-01/port/gi1/0/8 HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /project/proj-01 HTTP/1.1" 409 68
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /project/proj-02 HTTP/1.1" 409 68
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "PUT /project/proj-03 HTTP/1.1" 409 68
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /project/proj-01/connect_node HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /project/proj-02/connect_node HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /project/proj-02/connect_node HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
connectionpool.py          395 DEBUG    "POST /project/proj-03/connect_node HTTP/1.1" 200 0
connectionpool.py          248 INFO     Resetting dropped connection: 127.0.0.1
```

There is likely something odd going on with the way HTTP requests are being handled.

I will point out that I was against spinning up an actual server for these tests.  I was left out of the discussion -- you guys had it off-line without me, despite me being the person who raised the concern in the first place. I think I was just too exhausted by the whole thing to argue anymore.

I *still* think we shouldn't be spinning up a full web server -- the functionality that is being tested doesn't need it, and though it shouldn't have this much of an effect it *is* going to slow things down. In addition to real network activity, it means we can't use an in-memory db, so we're actually hitting the disk for each requests -- probably even doing a sync() on commit.

I don't know that I think debugging a performance problem with a dev server that isn't supposed to be fast in the first place is worthwhile -- if we want benchmarks we should run them against apache.

**Comment by henn** [comment] 2017-05-11 17:15
Re: running a full server, there was a debate (I was on the side of using flask's built-in server), and the vote was to use the dev server. @pjd-nu and @okrieg felt that it was necessary to quickly make a decision, so we did it at one of the HIL meetings.

Given the time I spent debugging/fixing this as part of #774, I'm tempted to to revert the client library tests if we can't stabilize them soon.

**Comment by zenhack** [comment] 2017-05-11 22:52
+1 for reverting if we can't solve this soon. I'd also like to get the dev server out of there one way or another -- it's adding complexity (and a big performance hit, even in the theoretical case where there's not something funny going on) without much tangible benefit.

**Comment by henn** [comment] 2017-06-07 18:26
FYI - we can treat this PR as a general *let's improve client library test performance*.

The client library tests caused Travis CI to go from ~15 mins to about an hour

**Comment by zenhack** [comment] 2017-06-07 18:46
I'd like to re-open the question of whether it's a good idea to actually spin up a web server for the client lib tests. I still maintain it isn't. But given these problems it seems worth discussing again (on the record this time...)

//cc @henn, @okrieg, @pjd-nu

**Comment by henn** [comment] 2017-06-14 18:04
@SahilTikale - Any updates on this?

**Comment by SahilTikale** [comment] 2017-06-14 18:34
@henn from the last email I was under an impression that we have frozen making of new PRs since we want to make a shift from `haas` to `hil` in our codebase. Therefore I was waiting for that to happen before I could submit PR to improve the efficiency of the tests. Let me know if that is not the case.

**Comment by zenhack** [comment] 2017-06-14 19:58
The freeze was as of tomorrow. But at this point it's probably a bot late.

Also, for the record, at the HIL meeting today we discussed and agreed that we don't need to spin up a real web server in the client tests.

**Comment by SahilTikale** [comment] 2017-06-28 17:57
@zenhack mentioned that we should not have a full fledged web server for these tests.
@henn mentioned moving this tests along with integrations tests.
I have a version of the current tests run faster than these tests, but I will not make the PR until #805 is resolved. Since there are difference of opinions on what approach is best, we should discuss it out here. 
@okrieg @pjd-nu

**Comment by zenhack** [comment] 2017-06-29 02:56
So, to clarify, at the meeting I raised the point that we've had different discussions with different groups of people and settled on different things; we were starting another one and I think it's proven a waste of time to have that conversation without everyone being able to participate, which means doing it here.

At the meeting I called into two weeks ago I thought we'd settled on not needing a web server for these at all. I gathered from the meeting today that at some point folks decided moving these into the integration tests would make sense? Unfortunately I wasn't around for the discussion/rationale behind that. I seem to recall @knikolla pointing out somewhere (probably on the original PR?) that these really weren't integration tests; they *are* simple unit tests.

@henn, can you fill me in on the reasoning here?

**Comment by shwsun** [comment] 2017-06-29 20:11
Ok, so here goes my $0.02:
I agree that the improving CI test is prioritized right after the renaming PR. This is the tech debt we have to pay because back in time we just want the client lib to done. We don't want to small fixes that will break other things or some hacking just to ease the pain. What we want is to reduce the CI running time to a reasonable time frame. I estimate it to be a job that will consume quite some time, and of cause afterwards we need some explicit requirements on the CI part.
@zenhack @henn @SahilTikale Do we need to come to some consensus next time?

**Comment by zenhack** [comment] 2017-06-29 20:40
I was actively against the current design at the time; my opinion re: the web server thing basically hasn't changed. The decision was made at an in-person meeting that was not recorded, and I was just out of steam on that PR; I didn't have the energy to protest anymore. If I wasn't so exhausted, I probably would have made more of a stink about it. When stuff turned out to be outright *broken* once we merged it, I was *pissed.* I drafted a number of comments that I had the good sense not to actually send.

I've really been pushing for doing as much as possible on the bug tracker; I think if we can agree that that kind of decision has to be hashed out here, we won't have an issue.

Also, that PR was a really pathological failure of process -- there were many, many dropped balls. Part of the problem is that it was just *enormous*, and had that we'd allowed it to be worked on for a *very* long time without real interaction with other developers. by the time I really dug into it, the *patch* had rather a lot of technical debt.

As far as how we go about fixing this, The lowest-hanging fruit is getting that web server out of there. Instead, we should use mock objects. Concrete benefits of this approach:

* Most importantly, I actually did some measurements, and the time is all going in to the server setup and/or network traffic. So cutting all of that out should have a big impact.
* Also, killing the web server will allow us to use an in-memory database for the sqlite run, like all of the other tests. This will improve things somewhat, though it won't affect the postgres run.
* It will be generally simpler; per my comments above, these are unit tests; they're supposed to focus on a specific chunk of the code.

To make this happen, we'd need a mock object to use as an HTTPClient. This is in large part the motivation for #777.

**Comment by naved001** [comment] 2017-06-30 14:13
>  these are unit tests; they're supposed to focus on a specific chunk of the code.

This might have been said before, but @knikolla once told me about this neat [requests-mock](https://pypi.python.org/pypi/requests-mock) library to mock out the HTTP requests. If all we want is unit tests for the client library, then we can use that instead of a web server, right?

**Comment by zenhack** [comment] 2017-06-30 17:07
Yeah, that might be even better.

**Comment by zenhack** [comment] 2017-07-13 16:28
So I spent a bit of time poking at requests-mock; it looks like it would be a big chunk of work to move this over to that, since we'd actually have to spec out the responses for each test in detail.

My inclination is to do the thing I outlined before (fix #777, then use a flask based mock object). If you want to put a label on it "functional testing" might be better than unit; this is true for a lot of what we have in the tests/unit/ directory. But the key thing is: this performance issue is really crippling as a developer, and I think this is the easiest way forward. I also that whatever you call these tests, they're *mostly* sensible, if we can fix the perf issue.

**Comment by knikolla** [comment] 2017-07-14 18:46
I agree with @zenhack.

**Comment by naved001** [comment] 2017-07-17 20:51
#827 fixes this.

**Comment by henn** [comment] 2017-07-18 20:24
#827 didn't parallelize the tests, even though it did reduce the time significantly.

Re-opening for that purpose.

**Closed** 2017-07-18 20:25 UTC
