### ISSUE TITLE
Migrate HaaS -> HIL

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#794] opened 2017-06-07 18:16 UTC
We began the slow transition of moving the HaaS name to HIL. Let's finish it in both the code and file names.

**Comment by zenhack** [comment] 2017-06-07 18:48
This is a duplicate of #602; can we close this and discuss there?

**Comment by naved001** [comment] 2017-06-08 22:43
Yeah, I am gonna close this issue then since it's a duplicate.

**Closed by naved001** 2017-06-08 22:43 UTC
