### ISSUE TITLE
Need way to track asynchronus status for operations

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#382] opened 2014-12-15 21:05 UTC
Currently, there is no way to view the status of an asynchronus operation like connect or disconnect network.

One way to achieve this is to create a handle system that would track pending and recently completed operations. The user would then poll this handle.

**Comment by zenhack** [comment] 2017-06-01 22:25
I think this is actually a duplicate of #427 (or vice-versa); what you're suggesting sounds like my proposal there.

(Just got the notification about you self-assigning).

**Comment by xuhang57** [comment] 2018-02-07 21:19
@zenhack @naved001 close this for now. please reopen if you think it's necessary.

**Closed by xuhang57** 2018-02-07 21:19 UTC
Labels: reliability

**Comment by zenhack** [comment] 2018-02-07 21:35
@naved001's pr solves this, so yeah we can close.
