### ISSUE TITLE
More descriptive error messages/status codes for APIErrors

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#191] opened 2014-08-01 05:45 UTC
It would be nice if the haas server returned more intelligible errors to the client. This should be achievable in a reasonably elegant way by adding appropriate functionality to the subclasses of `APIError`.

**Comment by xuhang57** [comment] 2018-01-30 19:48
@zenhack maybe we can close this for now?

**Comment by naved001** [comment] 2018-01-30 19:57
The issue isn't entirely solved. There's more discussion on the related issue #925 so I'll close this one in favor of that. Please reopen if you think this warrants a separate discussion.

**Closed by naved001** 2018-01-30 19:57 UTC
Labels: enhancement
