### ISSUE TITLE
Client library test  problem: the case of the disappearing config file

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#776] opened 2017-05-11 17:21 UTC
If one of the client library tests encounters an error, then another distracting error is generated in the teardown fixture saying that it can't remove the `haas.cfg` file.

It's not obvious what's causing this. Running everything under `strace` using `strace -ff py.test -x -v -s tests/unit/client.py` with setup.cfg changed to disabled `--boxed` shows only one unlink operation against the file -- the one that returns the error that py.test is complaining about.

How did the file get removed if only the test that generated it knew about it?

`create_setup()` in tests/unit/client.py is where all of this happens.

Starting with the code that's part of #774 should help in debugging.

@SahilTikale

**Comment by SahilTikale** [comment] 2017-05-31 15:35
> If one of the client library tests encounters an error, then another distracting error is generated in the teardown fixture saying that it can't remove the haas.cfg file.

If the test fails to execute (and not fails as intended) then that error may affect the tear down procedure. 
for each test, the create_setup() creates the necessary haas.cfg file, initializes the database, starts servers and populates them. After each test it destroys all of it including the config files and database. 

> How did the file get removed if only the test that generated it knew about it?

The test does not generate the file, it is generated before executing the test. Correct me if I misunderstood. 

I think once the test fails, and before next one starts the fixtures destroys the set up if it can (depending on what the error might be ) and  make a new setup in a new folder.  

Let me know if that clarifies the issue.

**Comment by zenhack** [comment] 2017-05-31 19:55
@henn, what is the exact error? (do you have a travis log you can link to?)

**Comment by naved001** [comment] 2017-07-17 14:52
this wouldn't be an issue once #827 is merged since we won't create or remove any config file.

**Closed** 2017-07-17 20:59 UTC
