### ISSUE TITLE
list_node and show_node rest api 

### ISSUE THREAD

**Issue by matsuuran** [CCI-MOC/hil#627] opened 2016-07-20 23:04 UTC
The call for `list_node` and `show_node` have the same url `/node/<is_free>` and `/node/<node>` respectively.  Easy change just wanted to document.  I will change `list_node` to `/node/list/<is_free>`.

**Comment by shwsun** [comment] 2016-08-10 17:28
@matsuuran I am wondering is this addressed by #619 ? I am a little confused about the first sentence.

**Comment by matsuuran** [comment] 2016-08-11 12:15
@shwsun 

lets just say you have a node named "all" or "free"  you would have a collision on the rest call.  It is just a small edge case

**Comment by shwsun** [comment] 2016-08-11 14:57
I see. It will cause a collision and we have to solve it. However, I would more like to keep the ``list_nodes`` rest call just like other ``list_xxx`` calls. Any other ideas?
//cc @zenhack @henn @SahilTikale @gsilvis

**Comment by zenhack** [comment] 2016-08-11 17:46
Could make the all/free a query parameter, e.g. to list free nodes:

    GET /node?state=free

Or something. This would also make it easy to add more filters in a backwards-compatible way, and if we wanted to we could coalesce things like list_project_nodes:

    GET /node?project=foo

But whether we want to do that is it's own discussion.

**Comment by shwsun** [comment] 2016-08-11 19:14
Actually this problem is caused by mistake, we should have ``GET /nodes`` for ``list`` calls, and ``GET /node/<nodename>`` for ``show`` calls. #635 solves this and it is no longer a concern for us.

**Closed** 2016-09-08 19:36 UTC
